### ISSUE TITLE
pyprismatic metadata alphaBeamMax default value

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#22]
The default value for alphaBeamMax is 0.024, though the docs say it should be in mrad.
I'm not sure how that has been impacting my previous simulations.

```python
>>> import pyprismatic as pr
>>> pr.Metadata().alphaBeamMax
0.024
```

**Comment by thomasaarholt** [comment]
The same goes for `integrationAngleMin` and `integrationAngleMax`, although I haven't been using those.

**Comment by apryor6** [comment]
Typo in the docs as there is no implicit conversion done like there is in the prismatic cli. There is some internal sanity checking performed, so for the case where you entered probeSemiangle = 20 (rad), it would have been truncated to whatever the maximum actual value was, so that is why you still get some result.

**Comment by thomasaarholt** [comment]
Ah! Thanks, I was about to comment on your second point after noticing your commits. Well done anticipating :)
