### ISSUE TITLE
Computation time of S-matrix increases with beam energy?

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#23]
I observe that increasing the beam energy from 80kV to 300kV means that calculating the probe takes a lot longer (near instant vs ~1 min on a non-gpu laptop). All that time is spent computing the "compact s-matrix". Could you explain why it takes longer? I tried doing some googling but found myself in way over my head.

**Comment by apryor6** [comment]
Sure, there's probably not much material on Google for this anway -- really the only literature is the two academic papers [here](http://prism-em.com/citeus/). 
The reason for the slowdown is because computing the compact s-matrix involves propagating a probe through the sample *for each relevant Fourier component of the FFT of the sample*, where a relevant Fourier component is one within the limiting scattering angle of the probe and aligned with the periodic downsampling function that is determined by the prism interpolation factor *f*. As you increase the energy, you are increasing the spatial resolution of the simulation, and thus there are more Fourier components that fit this criteria.
