### ISSUE TITLE
PyPrismatic defaulting to streaming unnecessarily?

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#49]
I just noticed that pyprismatic was taking 10x longer than prismatic on the same dataset with the same settings. I had set streaming-mode to "auto" on both setups.

Explicitly setting streaming-mode to "singlexfer" made it run in 1 minute instead of 10.

I'm not sure where the fault lies, or if this was a fluke.

**Comment by apryor6** [comment]
Single transfer mode should always be much faster than streaming mode. Streaming mode is only intended for cases where you _cannot_ use single transfer mode, and auto mode is there to provide a heuristic for inferring whether or not you need to use streaming mode (rather than the job running for some time and then crashing). It's just a heuristic though, so it is most certainly possible that auto mode sets it to streaming when it could successfully complete in single transfer mode.
