### ISSUE TITLE
Odd order of output 

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#87]
Prismatic version 1.2.1, since I've been unable to build it on Windows ("missing kernel32.lib" error)

I've noticed the following from time to time, definitely on Windows, and I think on Ubuntu as well.
The first "computing the probe positions" appears before the "waiting for GPU threads".
Is this a minor race condition?
![image](https://user-images.githubusercontent.com/2721423/94366517-209d1200-00d9-11eb-843b-553941a033e0.png)

Additionally, there is an odd "0" that gets printed from time to time?

![image](https://user-images.githubusercontent.com/2721423/94366606-b20c8400-00d9-11eb-8f39-764be40f7e4a.png)

Finally, here is an image showing "everything in order".
![image](https://user-images.githubusercontent.com/2721423/94366626-ca7c9e80-00d9-11eb-9835-c2687b62bf25.png)

**Comment by lerandc** [comment]
Not a problematic race condition! In each probe thread, a worker will check if it's time to print some output-- this happens whenever the current probe position is: 100, or, 1/10th of the total number of probes (as done by int divide). If your first worker gets to main work loop before all workers are launched, you'll see this effect, since the 0th probe is always the first print out.
