### ISSUE TITLE
Load settings in gui

### ISSUE THREAD

**Issue by thomasaarholt** [prism-em/prismatic#9]
(I'm just listing these issues as I'm finding them, things I mention are not necessarily a priority)

It would be nice to be able to save/load the settings used for the GUI, as it can be a bit tedious entering all the values manually each time one wants to run a simulation (especially if one kills the simulation because it ate up all my ram 😅  )

**Comment by apryor6** [comment]
I'm a fan of this idea, and am going to try to implement this today. The plan would be to allow for a params.txt file that contains simulation parameters. This will be written out every time a simulation is run from the gui, and the last params file will be loaded at startup. I'll also add a button to load a custom file.

This would be particularly nice because users could share an .xyz file and a params file with a colleague and you can be confident that you are replicating the exact same simulation.

**Comment by apryor6** [comment]
Didn't mean to close -- I'll close in the relevant commit once this is implemented.
